from . import hr_employee_inherit
from . import vm_faculty
from . import project_task_faculty_inherit
from . import vm_patient
from . import vm_visit_type
from . import account_analytic_line_inherit
from . import maintenance_equipment_inherit
from . import vm_site_employee
from . import vm_project_manager
from . import account_move_inherit
from . import vm_indication
from . import project_inherit
from . import vm_project_tracking
from . import expenses_report_detail
from . import hr_expense_sheet
